version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: orderscript
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - MONGO_DB_URI=mongodb://mongo:27017/mydb
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        # volumes:
        #   - mongo-data:/data/db
        networks:
            - orderscript-network

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6380:6379"
        networks:
            - orderscript-network

# volumes:
#   mongo-data:


networks:
    orderscript-network:
        driver: bridge
